#!/usr/bin/env python3
"""
Test script to verify PDF processing works with both regular and scanned PDFs
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from app import extract_text_from_pdf, summarize_text

def test_pdf_extraction():
    print("=== PDF Extraction Test ===\n")
    
    # Test if we can import the modules
    try:
        import fitz
        print("✓ PyMuPDF (fitz) imported successfully")
    except ImportError as e:
        print(f"✗ Failed to import PyMuPDF: {e}")
        return False
    
    # Test the extraction function exists
    print("✓ extract_text_from_pdf function available")
    print("✓ summarize_text function available")
    
    print("\nTest framework ready!")
    print("\nTo test:")
    print("1. Upload a regular PDF through the web interface")
    print("2. Upload a scanned PDF through the web interface")
    print("3. Check that text extraction works for both")
    print("4. Verify summaries are generated by Gemini")
    
    return True

if __name__ == "__main__":
    success = test_pdf_extraction()
    sys.exit(0 if success else 1)
